import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import RenderInput from "../components/RenderInput";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const outputConsole = (input: string) => {
    console.log(input);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RenderInput outputConsole={outputConsole} />
    </div>
  );
};

export default Home;
