import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CustomHooks from "../components/CustomHooks";
import FrameWorkList from "../components/FrameWorkList";
import MockServer from "../components/MockServer";
import ReduxAsync from "../components/ReduxAsync";
import RenderInput from "../components/RenderInput";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const outputConsole = (input: string) => {
    console.log(input);
  };

  const data = [
    {
      id: 1,
      item: "React",
    },
    {
      id: 2,
      item: "Angular",
    },
    {
      id: 3,
      item: "Vue",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RenderInput outputConsole={outputConsole} />
      <FrameWorkList frameworks={data} />
      <FrameWorkList />
      <MockServer />
      <ReduxAsync />
      <CustomHooks />
    </div>
  );
};

export default Home;
